eHubPortal/grails-app/domain/com/b2b/ehubportal/DocumentContentMapping.groovy
package com.b2b.ehubportal

class DocumentContentMapping {

    int docId
    int contentId
    String comm_sequence
    int version1
    String documentTypeId
    int contentTypeId
    int rowNum

    static constraints = {
    }

}

eHubPortal/grails-app/controllers/com/b2b/ehubportal/DocumentContentMappingController.groovy
package com.b2b.ehubportal

import grails.converters.JSON
import org.grails.web.json.JSONElement

class DocumentContentMappingController {

    private static final String DEFAULT_CHARSET = "UTF-8";
    DocumentContentMappingService documentContentMappingService

    def list() {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.documentContentMappingSorting.DOCID.toString() : sort

        println "before########## " + db + offset + limit + sort

        def www = documentContentMappingService.listDocumentContentMapping(db, offset, limit, sort)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] dcmCount = www.getHeaderField("Content-Range").split("/")
        int totalRows = Integer.parseInt(dcmCount[1])

        def params = [:]
        params.put("db", db)
        params.put("sort", sort)

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                println "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
                render(view: "index", model: [dcmList: yyy, dcmCount: totalRows, params: params])
            }
        } else {
            DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
            render(view: "index", model: [dcmList: yyy, dcmCount: totalRows, params: params])
        }
    }
	
	def reprocess(String cbfield) {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        //def filter1 = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.documentContentMappingSorting.DOCID.toString() : sort
        def filter = 'docid::'.concat(cbfield)

        println "before########## " + db + offset + limit + sort

        def www = documentContentMappingService.searchDocumentContentMapping(db, offset, limit, sort,filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] dcmCount = www.getHeaderField("Content-Range").split("/")

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                println "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
                render(view: "ContentID", model: [dcmList: yyy])
            }
        } else {
            DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
            render(view: "ContentID", model: [dcmList: yyy])
        }
    }

    def search() {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr
        def zzz = [:]

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.documentContentMappingSorting.DOCID.toString() : sort
        filter = filter == null ? 'docid::2201941' : filter

        println "before########## " + db + offset + limit + sort

        def www = documentContentMappingService.searchDocumentContentMapping(db, offset, limit, sort, filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] dcmCount = www.getHeaderField("Content-Range").split("/")

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                println "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                println jsonElement1.toString()
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                DocumentContentMapping domainDCM = new DocumentContentMapping(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + domainDCM.getDocId()
                render(view: "search", model: [dcmList: yyy, docId: domainDCM.getDocId()])
            }
        } else {
            DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
            render(view: "search", model: [dcmList: yyy, docId: sss.getDocId()])
        }
    }

    def delete() {
        JSONElement jsonElement;

        def db = params.getRequest().getParameter('db')
        def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        filter = 'docid::2201941' + "|version!::1"

        def www = documentContentMappingService.deleteDocumentContentMapping(db, filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement

        println "DCM RESPONSE CODE: " + xxx.getResult().getCode()

        if (xxx.getResult().getCode() == 200) {
            println "Delete successfully"
        } else {
            println "Fail to delete"
        }
    }
	
	def delete1(String cbfield ) {
        JSONElement jsonElement;

        def db = params.getRequest().getParameter('db')
        //def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        def filter = 'CONTENTID::'.concat(cbfield)
        println "contentid"+filter

        def www = documentContentMappingService.deleteDocumentContentMapping(db,filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement

        println "DCM RESPONSE CODE: "+ xxx.getResult().getCode()

        if (xxx.getResult().getCode()==200){
            println "Delete successfully"
        }
        else {
            println "Fail to delete"
        }
    }

	/*
    def getSearchContentId(String db, String result) {
        JSONElement jsonElement
        JSONElement jsonElement1
        String concatStr

        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        def filter = "docId::" + result.toString()

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset

eHubPortal/grails-app/controllers/com/b2b/ehubportal/MongoController.groovy
package com.b2b.ehubportal

class MongoController {

    private static final String DEFAULT_CHARSET = "UTF-8"
    MongoService mongoService

    //Need to pass in the contentid, collectionName, systemName
    def view() {
        def contentId = params.getRequest().getParameter('contentId')
        def collectionName = params.getRequest().getParameter('collectionName')
        def systemName = params.getRequest().getParameter('systemName')

        contentId = contentId == null ? '9786132' : contentId
        collectionName = collectionName == null ? 'DOCUMENT_CONTENT' : collectionName
        systemName = systemName == null ? 'eHub_mssql_QA' : systemName

        def test = mongoService.WebServiceLookup(contentId,collectionName,systemName)
        println "testing ##########"

        render(view: "view", model:[xmlString:test])
    }

    def download() {
        def contentId = params.getRequest().getParameter('contentId')
        def collectionName = params.getRequest().getParameter('DOCUMENT_CONTENT')
        def systemName = params.getRequest().getParameter('eHub_mssql_QA')

        contentId = contentId == null ? '9786132' : contentId
        collectionName = collectionName == null ? 'DOCUMENT_CONTENT' : collectionName
        systemName = systemName == null ? 'eHub_mssql_QA' : systemName

        def test = mongoService.WebServiceLookup(contentId,collectionName,systemName)
        if (test == null) {
            flash.message = "Document not found."
            redirect(action: 'view')
        } else {
            response.setContentType("APPLICATION/OCTET-STREAM")
            response.setHeader("Content-Disposition", "Attachment;Filename=\"${contentId}\"")
            def outputStream = response.getOutputStream()
            outputStream << test
            outputStream.flush()
            outputStream.close()
        }
    }
}

eHubPortal/grails-app/views/documentContentMapping/ContentID.gsp
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="main"/>

    <title><g:message code="docCM.label"/></title>

</head>

<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="pt-5 pb-2 mb-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item active">eHub</li>
                <li class="breadcrumb-item active">Flow</li>
                <li class="breadcrumb-item active" aria-current="page"><g:message code="workflow.label" /></li>
            </ol>
        </nav>
        <div class="d-flex align-items-center border-bottom">
            <h3 class="d-none d-sm-block">Document Content Mapping::</h3>
        </div>
    </div>

    <div class="col-lg-auto col-md-auto">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col"><g:message code="docCM.version.label"/></th>
                    <th scope="col"><g:message code="docCM.contentId.label"/></th>
                </tr>
                </thead>
                <tbody>
                <g:form action="delete1" controller="documentContentMapping"><button>DELETE</button>
                <g:each status="i" in="${dcmList}" var="dcm">
                    <tr>
                        <th><input type="checkbox" name="cbfield" value="${dcm.contentId}"/></th>
                        <td>${dcm.version1}</td>
                        <td>${dcm.contentId}</td>
                    </tr>
                </g:each>
                </g:form>
                </tbody>
            </table>
        </div>
    </div>
</main>
</body>
</html>

eHubPortal/grails-app/views/documentContentMapping/index.gsp
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="main"/>

    <title><g:message code="docCM.label"/></title>
</head>

<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="pt-5 pb-2 mb-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item active">eHub</li>
                <li class="breadcrumb-item active">Flow</li>
                <li class="breadcrumb-item active">Document</li>
                <li class="breadcrumb-item active" aria-current="page"><g:message code="docCM.label"/></li>
            </ol>
        </nav>

        <div class="d-flex align-items-center border-bottom">
            <h3 class="d-none d-sm-block">Document Content Mapping</h3>
        </div>
    </div>

    <div class="col-lg-auto col-md-auto">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col"><g:message code="docCM.docId.label"/></th>
                    <th scope="col"><g:message code="docCM.contentId.label"/></th>
                    <th scope="col"><g:message code="docCM.version.label"/></th>
                    <th scope="col"><g:message code="docCM.viewDownload.label"/></th>
                </tr>
                </thead>
                <tbody>
                <g:each status="i" in="${dcmList}" var="dcm">
                    <tr>
                        <td>${dcm.docId}</td>
                        <td>${dcm.contentId}</td>
                        <td>${dcm.version1}</td>
                        <td>
                            <g:link controller="mongo" action="view" params="[contentId: dcm.contentId]">
                                <span style="width:60px;height:10px"><button type="button" class="btn btn-info">View</button></span>
                            </g:link>
                            <g:link controller="mongo" action="download" params="[contentId: dcm.contentId]">
                                <span style="width:100px;height:10px"><button type="button" class="btn btn-success">Download</button></span>
                            </g:link></td>
                    </tr>
                </g:each>
                </tbody>
            </table>
        </div>
        <g:paginate controller="documentContentMapping" action="list" total="${dcmCount}" params="${params}"/>
    </div>
</main>
</body>
</html>

eHubPortal/grails-app/views/documentContentMapping/search.gsp
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="main"/>

    <title><g:message code="docCM.label"/></title>

</head>

<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="pt-5 pb-2 mb-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item active">eHub</li>
                <li class="breadcrumb-item active">Flow</li>
                <li class="breadcrumb-item active">Document</li>
                <li class="breadcrumb-item active" aria-current="page">DCM</li>
            </ol>
        </nav>
        <div class="d-flex align-items-center border-bottom">
            <h3 class="d-none d-sm-block">Document Content Mapping :: ${docId}</h3>
        </div>
    </div>

    <div class="col-lg-auto col-md-auto">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col"><g:message code="docCM.version.label"/></th>
                    <th scope="col"><g:message code="docCM.contentId.label"/></th>
                    <th scope="col"><g:message code="docCM.viewDownload.label"/></th>
                </tr>
                </thead>
                <tbody>
                <g:each status="i" in="${dcmList}" var="dcm">
                    <tr>
                        <td>${dcm.version1}</td>
                        <td>${dcm.contentId}</td>
                        <td>
                            <g:link controller="mongo" action="view" params="[contentId: dcm.contentId]">
                                <span style="width:60px;height:10px"><button type="button" class="btn btn-info">View</button></span>
                            </g:link>
                            <g:link controller="mongo" action="download" params="[contentId: dcm.contentId]">
                                <span style="width:100px;height:10px"><button type="button" class="btn btn-success">Download</button></span>
                            </g:link></td>
                    </tr>
                </g:each>
                </tbody>
            </table>
        </div>
    </div>
</main>
</body>
</html>