eHubPortal/grails-app/domain/com/b2b/ehubportal/Document.groovy
package com.b2b.ehubportal

class Document {
    int docId
    int parentId
    String docNo
    int docSize
    Date lastActionDate = new Date()
    int status
    String docFileName
    String senderMailboxId
    String receiverMailboxId
    String description
    String creationDate
    int version
    String createdBy
    String lastActionBy
    String lastAction
    Date sentDate = new Date()
    Date receiveDate=new Date()
    String senderCode
    String receiverCode
    String startTime
    int errorFlag
    int lastErrorTypeId
    int modifyVersion
    String windowSize
    String metadata
    String docTypeId
    String docFormat
    int internal_status
    int retryCount_short
    String oriDocFileName
    String direction
    String state
    int correlationId
    String agreementId
    String workflowId
    Date updateDateTime=new Date()
    Date documentDate=new Date()
    int documentStatus
    String previous_state
    int latest_sequenceOrder
    String last_successful_state
    int retryInterval_short
    String organizationId
    String split_parentChild
    String senderOrgId
    String receiverOrgId
    String forwardCorrelationId
    String lastErrorDateTime
    int lastErrorId
    String jbossId
    int retryCount_long
    int retryInterval_long
    int retryInterval
    int remainingRetry
    int priority
    String ves_transmissionId
    String timeStamp
    String control_number
    int queue_priority
    int rowNum

    static constraints = {
    }
}

eHubPortal/grails-app/controllers/com/b2b/ehubportal/DocumentContentMappingController.groovy
package com.b2b.ehubportal

import grails.converters.JSON
import org.grails.web.json.JSONElement

class DocumentContentMappingController {

    private static final String DEFAULT_CHARSET = "UTF-8";
    DocumentContentMappingService documentContentMappingService

    def list() {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.documentContentMappingSorting.DOCID.toString() : sort

        println "before########## " + db + offset + limit + sort

        def www = documentContentMappingService.listDocumentContentMapping(db, offset, limit, sort)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] dcmCount = www.getHeaderField("Content-Range").split("/")
        int totalRows = Integer.parseInt(dcmCount[1])

        def params = [:]
        params.put("db", db)
        params.put("sort", sort)

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                println "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
                render(view: "index", model: [dcmList: yyy, dcmCount: totalRows, params: params])
            }
        } else {
            DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
            render(view: "index", model: [dcmList: yyy, dcmCount: totalRows, params: params])
        }
    }
	
	def reprocess(String cbfield) {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        //def filter1 = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.documentContentMappingSorting.DOCID.toString() : sort
        def filter = 'docid::'.concat(cbfield)

        println "before########## " + db + offset + limit + sort

        def www = documentContentMappingService.searchDocumentContentMapping(db, offset, limit, sort,filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] dcmCount = www.getHeaderField("Content-Range").split("/")

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                println "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
                render(view: "ContentID", model: [dcmList: yyy])
            }
        } else {
            DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
            render(view: "ContentID", model: [dcmList: yyy])
        }
    }

    def search() {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr
        def zzz = [:]

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.documentContentMappingSorting.DOCID.toString() : sort
        filter = filter == null ? 'docid::2201941' : filter

        println "before########## " + db + offset + limit + sort

        def www = documentContentMappingService.searchDocumentContentMapping(db, offset, limit, sort, filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] dcmCount = www.getHeaderField("Content-Range").split("/")

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                println "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                println jsonElement1.toString()
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                DocumentContentMapping domainDCM = new DocumentContentMapping(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + domainDCM.getDocId()
                render(view: "search", model: [dcmList: yyy, docId: domainDCM.getDocId()])
            }
        } else {
            DocumentContentMapping sss = new DocumentContentMapping(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getDocId()
            render(view: "search", model: [dcmList: yyy, docId: sss.getDocId()])
        }
    }

    def delete() {
        JSONElement jsonElement;

        def db = params.getRequest().getParameter('db')
        def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        filter = 'docid::2201941' + "|version!::1"

        def www = documentContentMappingService.deleteDocumentContentMapping(db, filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement

        println "DCM RESPONSE CODE: " + xxx.getResult().getCode()

        if (xxx.getResult().getCode() == 200) {
            println "Delete successfully"
        } else {
            println "Fail to delete"
        }
    }
	
	def delete1(String cbfield ) {
        JSONElement jsonElement;

        def db = params.getRequest().getParameter('db')
        //def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        def filter = 'CONTENTID::'.concat(cbfield)
        println "contentid"+filter

        def www = documentContentMappingService.deleteDocumentContentMapping(db,filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement

        println "DCM RESPONSE CODE: "+ xxx.getResult().getCode()

        if (xxx.getResult().getCode()==200){
            println "Delete successfully"
        }
        else {
            println "Fail to delete"
        }
    }

	/*
    def getSearchContentId(String db, String result) {
        JSONElement jsonElement
        JSONElement jsonElement1
        String concatStr

        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        def filter = "docId::" + result.toString()

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset

eHubPortal/grails-app/controllers/com/b2b/ehubportal/WorkflowProcessController.groovy
package com.b2b.ehubportal

import grails.converters.JSON
import org.grails.web.json.JSONElement

class WorkflowProcessController {

    private static final String DEFAULT_CHARSET = "UTF-8";
    WorkflowProcessService workflowProcessService

    def list() {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.workflowProcessSorting.WORKFLOWID.toString() : sort

        println "before########## " + db + offset + limit + sort

        def www = workflowProcessService.listWorkflowProcess(db, offset, limit, sort)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement

        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] workflowProcessCount = www.getHeaderField("Content-Range").split("/")
        String[] range = workflowProcessCount[0].split("-")
        int totalRows = Integer.parseInt(workflowProcessCount[1])

        def params = [:]
        params.put("db", db)
        params.put("sort", sort)

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0)
                render "No data found"
            else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                WorkflowProcess sss = new WorkflowProcess(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getSequenceOrder()
                render(view: "index", model: [workflowProcessList: yyy, workflowProcessCount: totalRows, params: params])
            }
        } else {
            WorkflowProcess sss = new WorkflowProcess(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getSequenceOrder()
            render(view: "index", model: [workflowProcessList: yyy, workflowProcessCount: totalRows, params: params])
        }
    }

    def search() {
        JSONElement jsonElement;
        JSONElement jsonElement1;
        String concatStr

        def db = params.getRequest().getParameter('db')
        def offset = params.getRequest().getParameter('offset')
        def limit = params.getRequest().getParameter('max')
        def sort = params.getRequest().getParameter('sort')
        def filter = params.getRequest().getParameter('filter')

        db = db == null ? Enums.apiParamDb.ehub_aeon.toString() : db
        offset = offset == null ? '0' : offset
        limit = limit == null ? '10' : limit
        sort = sort == null ? Enums.workflowProcessSorting.SEQUENCEORDER.toString() : sort
        filter = filter == null ? '' : filter

        println "before########## " + db + offset + limit + sort

        def www = workflowProcessService.searchWorkflowProcess(db, offset, limit, sort, filter)
        jsonElement = JSON.parse(www.getInputStream(), DEFAULT_CHARSET)
        def xxx = (Result) jsonElement
        def yyy = [:]
        yyy = xxx.getResult().getData()

        String[] workflowProcessCount = www.getHeaderField("Content-Range").split("/")
        String[] range = workflowProcessCount[0].split("-")
        int totalRows = Integer.parseInt(workflowProcessCount[1])

        def params = [:]
        params.put("db", db)
        params.put("sort", sort)
        params.put("filter", filter)

        // if xxx.getResult().getData() return null value (cant get data, or only single records)
        if (yyy == null) {
            int searchIndex = jsonElement.toString().indexOf('"data":{', 0)
            if (searchIndex < 0) {
                render "No data found"
            }else {
                // If single records return, add square bracket for it
                String strBuild = jsonElement.toString()
                def startIndex = searchIndex + 7
                int endIndex = strBuild.indexOf('}', startIndex)
                concatStr = strBuild.substring(0, startIndex) + "[" + strBuild.substring(startIndex, endIndex + 1) + "]" + strBuild.substring(endIndex + 1, strBuild.length())

                jsonElement1 = JSON.parse(concatStr)
                def str2Json = (Result) jsonElement1

                yyy = str2Json.getResult().getData()
                WorkflowProcess sss = new WorkflowProcess(yyy[0])
                println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getWorkflowID()
                println 'totalRows123?' + totalRows
                render(view: "search", model: [workflowProcessList: yyy, workflowProcessCount: totalRows, workflowId: sss.getWorkflowID(), params: params])
            }
        } else {
            WorkflowProcess sss = new WorkflowProcess(yyy[0])
            println " 3>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  " + sss.getWorkflowID()
            println 'totalRows?' + totalRows
            render(view: "search", model: [workflowProcessList: yyy, workflowProcessCount: totalRows, workflowId: sss.getWorkflowID(), params: params])
        }

    }
}

eHubPortal/grails-app/views/document/displayUpdate.gsp
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="main"/>
    <title><g:message code="document.label" /></title>
</head>

<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="pt-5 pb-2 mb-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item active">eHub</li>
                <li class="breadcrumb-item active">Flow</li>
                <li class="breadcrumb-item active" aria-current="page"><g:message code="document.label" /></li>
            </ol>
        </nav>
            <div class="d-flex align-items-center border-bottom">
                <h3 class="d-none d-sm-block">Document</h3>
            </div>
    </div>

    <div class="container">
        <form action="displayUpdate"  controller="document">
            <table class="table table-hover">
                <tr>
                    <td>
                        <div class="col-xs-3">
                            <label for="docID">DOCID:</label><br>
                            <input type="text" class="form-control-sm" id="docID" placeholder="Enter Docid"
                                   name="docID">
                        </div>
                        <div class="col-xs-3">
                            <label for="docTypeId">DOCTYPEID:</label><br>
                            <input type="text" class="form-control-sm" id="docTypeId" placeholder="Enter Doctypeid"
                                   name="docTypeId">
                        </div>
                        <div class="col-xs-3">
                            <label for="status">STATUS:</label><br>
                            <input type="text" class="form-control-sm" id="status" placeholder="Enter Status" name="status">
                        </div>
                        <div class="col-xs-3">
                            <label for="status">FROM_DATE:</label><br>
                            <input type="date" class="form-control-sm" id="creationFromDate" placeholder="Enter From Date" name="creationFromDate">
                        </div>
                    </td>
                    <td>
                        <div class="col-xs-3">
                            <label for="status">SENDERMAILBOXID:</label><br>
                            <input type="text" class="form-control-sm" id="senderMailboxId"
                                   placeholder="Enter Sendermailboxid" name="senderMailboxId">
                        </div>
                        <div class="col-xs-3">
                            <label for="receiverMailboxId">RECEIVERMAILBOXID:</label><br>
                            <input type="text" class="form-control-sm" id="receiverMailboxId"
                                   placeholder="Enter Receivermailboxid" name="receiverMailboxId">
                        </div>
                        <div class="col-xs-3">
                            <label for="docFileName">DOCFILENAME:</label><br>
                            <input type="text" class="form-control-sm" id="docFileName" placeholder="Enter Docfilename"
                                   name="docFileName">
                        </div>
                        <div class="col-xs-3">
                            <label for="docFileName">TO_DATE:</label><br>
                            <input type="date" class="form-control-sm" id="creationToDate" placeholder="Enter To Date" name="creationToDate">
                        </div>
                    </td>
                </tr>
            </table>
            <br>
            <button class="btn-group-sm">SEARCH</button>
        </form>
    </div>

    <div class="col-lg-auto col-md-auto">
        <div class="table-responsive">
            <table class="table table-hover">

            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">#</th>
                <th scope="col"><sup><g:message code="document.docid.label"/></sup></th>
                <th scope="col"><sup><g:message code="document.status.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.docfilename.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.doctype.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.sendermailboxid.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.receiverMailboxId.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.version.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.creationdate.label" /></sup></th>
                <th scope="col"><sup><g:message code="document.symbol" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</sup></th>
            </tr>
            </thead>

            <tbody>
            <br/>
            <g:form action="reprocess" controller="document"> <button>REPROCESS</button>
                <g:each status="i" in="${documentSearch}" var="document">
                    <tr>
                        <th><input type="checkbox" name="checklist" value="${document.docId}"/></th>
                        <th scope="row">${document.rowNum}</th>
                        <td><small>${document.docId}</small></td>
                        <td><small>${document.status}</small></td>
                        <td><small>${document.docFileName}</small></td>
                        <td><small>${document.docTypeId}</small></td>
                        <td><small>${document.senderMailboxId}</small></td>
                        <td><small>${document.receiverMailboxId}</small></td>
                        <td><small>${document.version}</small></td>
                        <td><small>${document.creationDate}</small></td>


                        <td>
                            <g:link action="metadata" controller="document" params="${[categoryName: document.docId]}"><asset:image src="LastImages.jpg" width="20" height="20" /></g:link>
                            <g:link action="search" controller="workflowProcess" params="${[filter: "workflowId::" +  document.workflowId]}"><asset:image src="ImagesViews.jpg" width="20" height="20" /></g:link>
                            <g:link action="search" controller="documentContentMapping" params="${[filter: "docId::" + document.docId]}"><asset:image src="EyeView.png" width="20" height="20" /></g:link></td>
                    </tr>
                </g:each>
            </g:form>
            </tbody>
            </table>
            <div>
                <g:paginate controller="document" action="displayUpdate" total="${documentCount}" params="${params}"/>
            </div>
            </div>
    </div>
</main>
</body>
</html>

eHubPortal/grails-app/views/document/list.gsp
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="main"/>

    <title><g:message code="document.label" /></title>
</head>

<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="pt-5 pb-2 mb-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item active">eHub</li>
                <li class="breadcrumb-item active">Flow</li>
                <li class="breadcrumb-item active" aria-current="page"><g:message code="document.label" /></li>
            </ol>
        </nav>
        <div class="d-flex align-items-center border-bottom">
            <h3 class="d-none d-sm-block">Document</h3>
        </div>
    </div>

    <div class="col-lg-auto col-md-auto">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>

                    <th scope="col">#</th>
                    <th scope="col"><sup><g:message code="document.docid.label"/></sup></th>
                    <th scope="col"><sup><g:message code="document.status.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.docfilename.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.doctype.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.sendermailboxid.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.receiverMailboxId.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.version.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.creationdate.label" /></sup></th>

                </tr>
                </thead>
                <tbody>
                <g:each status="i" in="${documentList}" var="document">
                    <tr>

                        <th scope="row">${document.rowNum}</th>
                        <td><small>${document.docId}</small></td>
                        <td><small>${document.status}</small></td>
                        <td><small>${document.docFileName}</small></td>
                        <td><small>${document.docTypeId}</small></td>
                        <td><small>${document.senderMailboxId}</small></td>
                        <td><small>${document.receiverMailboxId}</small></td>
                        <td><small>${document.version}</small></td>
                        <td><small>${document.creationDate}</small></td>

                    </tr>
                </g:each>
                </tbody>
            </table>
        </div>

        <g:paginate controller="document" action="list" total="${documentCount}" params="${params}"/>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <asset:javascript src="jquery-3.2.1.min.js"/>
    <asset:javascript src="popper.min.js"/>
    <asset:javascript src="bootstrap.min.js"/>
</main>
</body>
</html>

eHubPortal/grails-app/views/document/reprocessBatch.gsp
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="main"/>

    <title><g:message code="document.label" /></title>
</head>

<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="pt-5 pb-2 mb-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/home">Home</a></li>
                <li class="breadcrumb-item active">eHub</li>
                <li class="breadcrumb-item active">Flow</li>
                <li class="breadcrumb-item active" aria-current="page"><g:message code="document.label" /></li>
            </ol>
        </nav>
        <div class="d-flex align-items-center border-bottom">
            <h3 class="d-none d-sm-block">Reprocess Batch</h3>
        </div>
    </div>

    <div class="col-lg-auto col-md-auto">
        <g:link controller="document" action="reprocessBatch"><button>REFRESH</button></g:link>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col"><sup><g:message code="document.docid.label"/></sup></th>
                    <th scope="col"><sup><g:message code="document.status.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.docfilename.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.doctype.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.sendermailboxid.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.receiverMailboxId.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.version.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.creationdate.label" /></sup></th>
                    <th scope="col"><sup><g:message code="document.symbol" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</sup></th>
                </tr>
                </thead>
                <tbody>
                <g:each status="i" in="${documentSearch}" var="document">
                    <tr>

                        <th scope="row">${document.rowNum}</th>
                        <td><small>${document.docId}</small></td>
                        <td><small>${document.status}</small></td>
                        <td><small>${document.docFileName}</small></td>
                        <td><small>${document.docTypeId}</small></td>
                        <td><small>${document.senderMailboxId}</small></td>
                        <td><small>${document.receiverMailboxId}</small></td>
                        <td><small>${document.version}</small></td>
                        <td><small>${document.creationDate}</small></td>
                        <td>
                            <g:link action="metadata" params="${[categoryName: document.docId]}"><asset:image src="LastImages.jpg" width="20" height="20" /></g:link>
                            <g:link action="search" controller="workflowProcess" params="${[filter: "workflowId::" + document.workflowId]}"><asset:image src="ImagesViews.jpg" width="20" height="20" /></g:link>
                            <g:link action="search" controller="documentContentMapping" params="${[filter: "docId::" +  document.docId]}"><asset:image src="EyeView.png" width="20" height="20" /></g:link>
                        </td>
                    </tr>
                </g:each>
                </tbody>
            </table>
        </div>

        <g:paginate controller="document" action="reprocessBatch" total="${documentCount}" params="${params}"/>
    </div>
</main>
</body>
</html>